### PR TITLE
Add type stubs

### PR DESCRIPTION
**Pull request by pvcnt**
Those stubs are generated from the generated API documentation, with fixes provided in #15 and #16.

### CODE REVIEW

**Comment by pvcnt** [comment]
Also, would it be possible to create a new release with my recent changes?

**Comment by inducer** [comment]
Is there a way to automate the generation, or at least have a CI job that checks that they're up to date?

**Comment by inducer** [comment]
(And sure, I'd be happy to roll a release once we're done here.)

**Comment by pvcnt** [comment]
There seems to be [a library](https://crates.io/crates/pyo3-stub-gen) to automatically generate those, but with limitations. I'm not familiar enough with Rust/Maturin to know how to wire it.

The following command can be used to validate the stubs:
```
python3 -m mypy.stubtest --ignore-missing-stub starlark
```
I need to write it into the workflow.

**Comment by pvcnt** [comment]
I added a validation step. It's inside the "pytest" job, because I need the built module to be able to test stubs, and preferred not to create yet another job building the wheels.

Note: The `--ignore-missing-stub` is here because otherwise mypy complains about the `starlark.starlark` module that is not present in the stubs. That module is internal and should not be (maybe prefixing it with an underscore would be a good way to signal it btw, but that is another story).

**Comment by inducer** [comment]
Thanks for adding the validation step. Upon playing around with it a bit, I noticed that passing `--ignore-missing-stub` will also ignore errors from stubs that are genuinely missing. (I tried by adding a dummy getter somewhere.) I tried to address this, but I've so far been unsuccessful.

**Comment by pvcnt** [comment]
I added another way to handle this via an allowlist. It specifies a list of modules where to ignore errors. It should ignore errors related to `starlark.starlark`, but not those related to `starlark`. Please note that this checker is by no means perfect, the docs mention a lot of limitations. It's really a best effort thing.

**Comment by inducer** [comment]
Thanks! That seems to do the trick.

**Comment by inducer** [comment]
A new release is on the way.

**Pull request merged**
